
###
//Add to cart
POST http://localhost:3000/api/cart/add
Content-Type: application/json

{
    "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2ViMzM0YTE1ZDE3NjUyNzU0Nzk2MyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg5NDAzODMsImV4cCI6MTc0ODk0MTg4M30.s05mg9BelaBe2wDp79MhJ9rvJjYz1wUdXRVatPcPSVg",
    "productId": "12345",
    "name": "Awesome Item",
    "price": 19.99,
    "quantity": 1
}
###
// Remove from Cart
POST http://localhost:3000/api/cart/remove
Content-Type: application/json

{
    "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2ViMzM0YTE1ZDE3NjUyNzU0Nzk2MyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg5NDAzODMsImV4cCI6MTc0ODk0MTg4M30.s05mg9BelaBe2wDp79MhJ9rvJjYz1wUdXRVatPcPSVg",
    "productId": "12345",
    "name": "Awesome Item",
    "price": 19.99,
    "quantity": 1
}

###
// Remove all from Cart
POST http://localhost:3000/api/cart/remove/all
Content-Type: application/json

{
    "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2ViMzM0YTE1ZDE3NjUyNzU0Nzk2MyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg5NDAzODMsImV4cCI6MTc0ODk0MTg4M30.s05mg9BelaBe2wDp79MhJ9rvJjYz1wUdXRVatPcPSVg"
}