@baseUrl=http://localhost:3000

GET {{baseUrl}}/api/product/all

### Add a new Product

POST {{baseUrl}}/api/product/add
Content-Type: application/json

{
  "slug": "breed-dry-dog-foode",
  "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347629/dogFood_ksds31.png",
  "stars": 5,
  "name": "Breed Dry Dog Food",
  "price": 100,
  "tag": "-40%",
  "numOfReviews": 35,
  "discountedPrice": 140,
  "description": "High-quality dry dog food specially formulated for specific breeds. Packed with essential nutrients to keep your pet healthy and strong.",
  "category": "Pet Supplies",
  "specialCategory": "Flash Sales"
}

### Remove Product

DELETE {{baseUrl}}/api/product/remove
Content-Type: application/json

{
  "_id":"68650b14314898ed2ba73668"
}

###
PUT {{baseUrl}}/api/product/edit
Content-Type: application/json

{
  "_id":"68628375edf189cb6baa0da1",
  "name":"Nothing"
}


### Get all products
GET {{baseUrl}}/api/product/all