//Get all users
GET http://localhost:3000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzlhMzVmYmUzY2JlNmU5ODIzNWVjZCIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg5Mzk4OTYsImV4cCI6MTc0ODk0MDE5Nn0.NgZgoK3UdFfmO0dD3Ig0fCv4ZCYc7himb7EMh2fIhkk
###
//Get new access token
POST http://localhost:3000/api/auth/token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzlhMzVmYmUzY2JlNmU5ODIzNWVjZCIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg4NDkxODgsImV4cCI6MTc0OTQ1Mzk4OH0.CWwaVrqDXSNvY5C8lvzZxI92xiCihOiRwtfE8mmI3a0"
}
###
//Logout (clears accessToken)

DELETE http://localhost:3000/api/auth/logout
Content-Type: application/json


###
//Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password":"123"
}

###


//Sign up new user
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name":"Toni",
    "email": "test@gmail.com",
    "password":"123"
}

###Fetching user id
GET http://localhost:3000/api/auth/me
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2ViMzM0YTE1ZDE3NjUyNzU0Nzk2MyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NDkxOTIyNTcsImV4cCI6MTc0OTE5MzE1N30.PFd7SFUEkSRimAWOzjp5Z7Nm9xxwiWDiPlz4zXnszbQ
